### ISSUE TITLE
aspecty.js is missing when installed from npmjs

### ISSUE THREAD

**Issue by chonla** [tomhodgins/cssplus#5]
I'm wondering if I did something wrong. I have installed cssplus from npmjs but there is no aspecty.js included.

Any idea?

**Comment by tomhodgins** [comment]
@chonla Great catch, I accidentally left aspecty and xpathy off the `files` property in the package.json file. 🤦‍♂️ I've updated this to v0.1.0 to include these now, so let me know if that works for you!

**Comment by chonla** [comment]
It works. Thank you for prompt response.

Anyway, I'm not sure if this is your intention. The package version is now 0.1.0 but the js files themselves are still 0.0.12.

**Comment by tomhodgins** [comment]
Ah, thanks again @chonla :D <3

**Comment by chonla** [comment]
no problem :)
